/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */

import service.TransaksiService;
import model.Transaksi;
import java.io.FileWriter;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TransaksiPemasukan;
import model.TransaksiPengeluaran;

public class KeuanganFrame extends javax.swing.JFrame {

    /**
     * Creates new form KeuanganFrame
     */
    private TransaksiService service = new TransaksiService();
    
    
    public KeuanganFrame() {
        initComponents();
        setLocationRelativeTo(null);
        cmbKategori.addItem("Pemasukan");
        cmbKategori.addItem("Pengeluaran");
        loadTable();
    }
    
    //memuat ulang data kedalam jtabel
    private void loadTable() {
        
        //model tabel dengan nama kolom
        DefaultTableModel model = new DefaultTableModel(new Object[]{"Tanggal", "Keterangan", "Nominal", "Kategori"}, 0);
        
        //mengambil semua transaksi dari service 
        for (Transaksi t : service.getAll()){
            model.addRow(new Object[]{
                t.getTanggal(),
                t.getKeterangan(),
                t.getNominal(),
                t.getKategori()
            });
        }
        //menampilkan model ke tabel gui
        tblTable.setModel(model);
        lblSaldo.setText("Rp " + service.getTotalSaldo());// menampilkan total saldo ke label
    }
    
    //mengosongkan semua input setelah tambah/ubah/hapus
 private void clearForm(){
     txtKeterangan.setText("");
     txtNominal.setText("");
     cmbKategori.setSelectedIndex(0);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJdudul = new javax.swing.JLabel();
        lblKeterangan = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        lblNominal = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        txtNominal = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnExportTxt = new javax.swing.JButton();
        btnExportJson = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        lblTotalSaldo = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJdudul.setBackground(new java.awt.Color(255, 51, 153));
        lblJdudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJdudul.setText("APLIKASI KEUANGAN PRIBADI");

        lblKeterangan.setBackground(new java.awt.Color(255, 51, 153));
        lblKeterangan.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblKeterangan.setText("Keterangan");

        lblNominal.setBackground(new java.awt.Color(255, 51, 153));
        lblNominal.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNominal.setText("Nominal");

        lblKategori.setBackground(new java.awt.Color(255, 51, 153));
        lblKategori.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblKategori.setText("Kategori");

        cmbKategori.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemasukan", "Pengeluaran" }));

        btnTambah.setBackground(new java.awt.Color(255, 51, 153));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 51, 153));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 153));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnExportTxt.setBackground(new java.awt.Color(255, 51, 153));
        btnExportTxt.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnExportTxt.setText("EXPORT TXT");
        btnExportTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportTxtActionPerformed(evt);
            }
        });

        btnExportJson.setBackground(new java.awt.Color(255, 51, 153));
        btnExportJson.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnExportJson.setText("EXPORT JSON");
        btnExportJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportJsonActionPerformed(evt);
            }
        });

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTable);

        lblTotalSaldo.setBackground(new java.awt.Color(255, 51, 153));
        lblTotalSaldo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTotalSaldo.setText("Total Saldo :");

        lblSaldo.setBackground(new java.awt.Color(255, 51, 204));
        lblSaldo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSaldo.setText("Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(btnExportTxt)
                .addGap(49, 49, 49)
                .addComponent(btnExportJson)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNominal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKeterangan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNominal)
                            .addComponent(cmbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(47, 47, 47)
                                .addComponent(btnUbah)
                                .addGap(48, 48, 48)
                                .addComponent(btnHapus)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtKeterangan)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblJdudul, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblJdudul, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportTxt)
                    .addComponent(btnExportJson))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //fungsi untuk menambahkan transaksi ke tabel
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
      
           String tanggal = LocalDate.now().toString();//mengambil tanggal otomatis hari ini
           String ket = txtKeterangan.getText(); //mengambil teks dari inputan user
           double nominal = Double.parseDouble(txtNominal.getText()); //mengubah  input nominal dari teks ke angka
           String kategori = cmbKategori.getSelectedItem().toString(); // mengambil kategori dari combo box
           
          Transaksi transaksi;
          
          // INHERITANCE + POLYMORPHISM
          
          if (kategori.equals("Pemasukan")){
              transaksi = new TransaksiPemasukan(tanggal, ket, nominal);
          }else{
              transaksi = new TransaksiPengeluaran(tanggal, ket, nominal);
          }
              //  memakai service
           service.tambah(transaksi);
           
           // refresh tampilan tabel & saldo
           tampilData();
           tampilSaldo();
           
           JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");
       
    }//GEN-LAST:event_btnTambahActionPerformed

    //fungsi untuk mengubah data transaksi
    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed

        int row = tblTable.getSelectedRow();// cek apakah user memilih baris di tabel
       if (row == -1){
           JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah");
           return;
       }
       
       
           String tanggal = LocalDate.now().toString();
           String ket = txtKeterangan.getText();
           double nominal = Double.parseDouble(txtNominal.getText());
           String kategori = cmbKategori.getSelectedItem().toString();
           
           Transaksi transaksi;
           
           // INHERITANCE  pilih objek sesuai kategori
           if (kategori.equals("Pemasukan")){
               transaksi = new TransaksiPemasukan(tanggal, ket, nominal);
           }else{
               transaksi = new TransaksiPengeluaran(tanggal, ket, nominal);
           }
           service.ubah(row, transaksi);
           tampilData();
            tampilSaldo();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
       
    }//GEN-LAST:event_btnUbahActionPerformed

    //fungsi untuk menghapus data transaksi
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tblTable.getSelectedRow();
        
        
        //jika belum memilih baris
        if (row == -1){
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus");
            return;
        }
        
        //mengapus transaksi di index yang di pilih
        service.hapus(row);
        tampilData();
        tampilSaldo();

        JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

    }//GEN-LAST:event_btnHapusActionPerformed
private void tampilData(){
    DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
    model.setRowCount(0);
    
    for (Transaksi t : service.getAll()){
        model.addRow(new Object[]{
            t.getTanggal(),
             t.getKeterangan(),
             t.getNominal(),
            t.getKategori()
        });
    }
}
private void tampilSaldo(){
    lblSaldo.setText("Rp. " + service.getTotalSaldo());
    
}
    //fungsi untuk export semua transaksi ke file txt
    private void btnExportTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportTxtActionPerformed
       try{
           
           //membuat file txt baru
           FileWriter fw = new FileWriter("data_keuangan.txt");
           
           //menulis setiap transaksi ke dalam file
           for (Transaksi t : service.getAll()){
               fw.write(
                        t.getTanggal() + " | " +
                                t.getKeterangan() + " | " +
                                t.getNominal() + " | " +
                                t.getKategori() + "\n" );
           }
           //menutup file
           fw.close();
           JOptionPane.showMessageDialog(this, "Export TXT berhasil!");
       }catch (Exception e){
           JOptionPane.showMessageDialog(this, "Gagal export TXT");
       }
    }//GEN-LAST:event_btnExportTxtActionPerformed

    //fungsi untuk export data ke json
    private void btnExportJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportJsonActionPerformed
       try{
           //membuat file json baru
           FileWriter fw = new FileWriter("data_keuangan.json");
           fw.write("[\n");
           
           int i = 0;
           
           //loop setiap transaksi
           for (Transaksi t : service.getAll()){
               
               //menulis objek json
               fw.write("  {\n");
               fw.write("    \"tanggal\": \"" + t.getTanggal() + "\",\n");
               fw.write("    \"keterangan\": \"" + t.getKeterangan() + "\",\n");
               fw.write("    \"nominal\": \"" + t.getNominal() + "\",\n");
               fw.write("    \"kategori\": \"" + t.getKategori() + "\"\n");
               fw.write("  }");
               
               //tambahkan koma kecuali di item terakhir
               if (i < service.getAll().size() - 1) fw.write(",");
               fw.write("\n");
               i++;
           }
           
           fw.write("]");
           fw.close();
           
           JOptionPane.showMessageDialog(this, "Export JSON berhasil!");
       }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Gagal export JSON");
       }

    }//GEN-LAST:event_btnExportJsonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeuanganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeuanganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeuanganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeuanganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeuanganFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportJson;
    private javax.swing.JButton btnExportTxt;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJdudul;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblNominal;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTotalSaldo;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables
}
